#!/usr/bin/env python3
"""DK-03: convert the recovered theory source to the official TMLR template.

Body text is copied unchanged. Only the preamble, the title block and the
bibliography style are rewritten, and every rewrite is printed as a log line so
the conversion is auditable.

Outputs, in --outdir:
    paper_common.tex     shared preamble, title, abstract and the whole body
    tmlr_submission.tex  wrapper: anonymous build (\\usepackage{tmlr})
    tmlr_named.tex       wrapper: named build (preprint option)
    tmlr.sty, tmlr.bst, fancyhdr.sty, references.bib, fig_*.pdf

Usage:
    python3 convert_to_tmlr.py --source <dir> --template <dir> --outdir <dir>
"""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

# Packages the TMLR style supplies or overrides; loading them again fights it.
DROP_PACKAGES = {
    "inputenc": "tmlr.sty sets T1 fontenc and lmodern; utf8 is the modern default",
    "fontenc": "tmlr.sty loads [T1]{fontenc}",
    "geometry": "tmlr.sty sets the TMLR page geometry",
    "mathptmx": "TMLR uses its own (Computer Modern / lmodern) fonts",
    "helvet": "same",
    "courier": "same",
    "natbib": "tmlr.sty loads natbib itself; a second load clashes on options",
    "fancyhdr": "tmlr.sty loads fancyhdr and sets the TMLR running head",
}

# Line breaks are set by hand: the TMLR title block is narrower than the
# source's, and unbroken lines wrap badly (a line ending in "Level:" alone).
TITLE = (
    "Unified Intelligence Theory and the\\\\\n"
    "Artificial Intelligence Level:\\\\\n"
    "A Cumulative, Harness-Measurable Hierarchy\\\\[6pt]\n"
    "{\\large Five Conceptual Intelligence Families, Six Measurable Coordinates,\\\\\n"
    "a Gated U0--U\\Om{} Scale, and the AI-Level Score of a Base Model\\\\\n"
    "Across a Standardized Harness Ladder}"
)

# Author order follows the amended public v2.6 PDF. DK-02 must confirm order,
# affiliation and corresponding author with all three authors before submission.
AUTHOR = (
    "\\author{\\name Chengshuai Yang \\email spiritai@platformai.org \\\\\n"
    "      \\addr NextGen PlatformAI C Corp, USA\n"
    "      \\AND\n"
    "      \\name Ting Xue \\email \\\\\n"
    "      \\addr NextGen PlatformAI C Corp, USA\n"
    "      \\AND\n"
    "      \\name Dingyi Kang \\email \\\\\n"
    "      \\addr NextGen PlatformAI C Corp, USA}"
)

# Layout repairs the narrower TMLR text block requires. Each is a pure
# reformatting of the same mathematics; none changes a symbol or a value.
LAYOUT_FIXES: list[tuple[str, str, str]] = [
    (
        "z_{U,n}(A) = \\prod_{X \\in \\{C, I, O, SA\\}} \\mathbb 1[X(A) \\ge X_n] \\cdot "
        "\\mathbb 1[S_{\\mathrm{net}}(A, T_n, H \\le H_n) \\ge p_n] \\cdot K_{U,<n}(A),\n"
        "\\qquad A \\models U_n \\iff z_{U,n}(A) = 1,",
        "\\begin{aligned}\n"
        "z_{U,n}(A) &= \\prod_{X \\in \\{C, I, O, SA\\}} \\mathbb 1[X(A) \\ge X_n] \\cdot "
        "\\mathbb 1[S_{\\mathrm{net}}(A, T_n, H \\le H_n) \\ge p_n] \\cdot K_{U,<n}(A),\\\\\n"
        "A &\\models U_n \\iff z_{U,n}(A) = 1,\n"
        "\\end{aligned}",
        "the U-gate display overflowed the TMLR text block by 14.9pt; "
        "set on two aligned lines instead of one",
    ),
    (
        "\\usepackage{amsmath,amssymb,amsthm,mathtools}",
        "\\usepackage{amsmath,amssymb,amsthm,mathtools}\n\\usepackage{dsfont}",
        "loaded dsfont, which supplies a real indicator glyph (see the next fix)",
    ),
    (
        "\\mathbb 1[X(A) \\ge X_n] \\cdot \\mathbb 1[S_{\\mathrm{net}}",
        "\\mathds{1}[X(A) \\ge X_n] \\cdot \\mathds{1}[S_{\\mathrm{net}}",
        "the two indicator functions in the U gate used \\mathbb 1; the AMS blackboard "
        "font has no digits, so both printed as a wrong symbol in the published v2.6 PDF "
        "as well. \\mathds{1} prints the intended indicator",
    ),
]

WRAPPER = """%% DK-03 {mode} build of the theory paper in the official TMLR template.
%% Generated by tmlr-prep/dk03/convert_to_tmlr.py - do not edit by hand.
\\documentclass[10pt]{{article}}
{option}\\usepackage{{tmlr}}

%% PDF metadata author list. Empty in the anonymous build: TMLR rejects
%% submissions that identify their authors, metadata included.
\\newcommand{{\\pdfauthorlist}}{{{authors}}}

\\input{{paper_common.tex}}
"""


def convert(source: Path, outdir: Path, template: Path) -> list[str]:
    log: list[str] = []
    text = (source / "main.tex").read_text()
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    in_fancy_block = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith("\\documentclass"):
            log.append("dropped \\documentclass (the wrapper supplies it, at 10pt as TMLR expects)")
            i += 1
            continue

        if stripped.startswith("\\pdfoutput"):
            log.append("dropped \\pdfoutput=1 (arXiv-specific; OpenReview takes the PDF as built)")
            i += 1
            continue

        pkg = re.match(r"\\usepackage(?:\[[^\]]*\])?\{([^}]*)\}", stripped)
        if pkg:
            names = [n.strip() for n in pkg.group(1).split(",")]
            if any(n in DROP_PACKAGES for n in names):
                for n in names:
                    if n in DROP_PACKAGES:
                        log.append(f"dropped \\usepackage{{{n}}} - {DROP_PACKAGES[n]}")
                i += 1
                continue

        # the source's own running-head block, replaced by TMLR's
        if stripped.startswith("\\pagestyle{fancy}"):
            in_fancy_block = True
            log.append("dropped the source's fancyhdr running-head block (TMLR sets its own head)")
        if in_fancy_block:
            if stripped.startswith("\\setlength{\\headheight}"):
                in_fancy_block = False
            i += 1
            continue

        # manual title block -> TMLR \title/\author/\maketitle
        # float tuning, inserted just before the document body
        if stripped.startswith("\\newcommand{\\Om}"):
            out.append("%% Float placement, retuned for the narrower TMLR text block. LaTeX's")
            out.append("%% defaults leave this paper (46 tables) with table-only pages and wide")
            out.append("%% gaps; these are the standard parameters, and they move no content.")
            out.append("\\renewcommand{\\topfraction}{0.9}")
            out.append("\\renewcommand{\\bottomfraction}{0.7}")
            out.append("\\renewcommand{\\textfraction}{0.08}")
            out.append("\\renewcommand{\\floatpagefraction}{0.75}")
            out.append("\\setcounter{topnumber}{3}")
            out.append("\\setcounter{bottomnumber}{2}")
            out.append("\\setcounter{totalnumber}{4}")
            out.append("%% Keep floats inside the section that introduces them. Without this,")
            out.append("%% tables drift above their own heading and a section reads as empty.")
            out.append("\\usepackage[section]{placeins}")
            out.append("%% placeins only guards \\section; this paper's tables belong to")
            out.append("%% subsections, so add the same barrier there.")
            out.append("\\let\\dkoldsubsection\\subsection")
            out.append("\\renewcommand{\\subsection}{\\FloatBarrier\\dkoldsubsection}")
            out.append("\\let\\dkoldsubsubsection\\subsubsection")
            out.append("\\renewcommand{\\subsubsection}{\\FloatBarrier\\dkoldsubsubsection}")
            out.append("")
            log.append(
                "layout: retuned the float placement parameters (topfraction, textfraction, "
                "floatpagefraction, totalnumber) and confined floats to their own section "
                "with placeins, at section, subsection and subsubsection level - the "
                "source's settings leave table-only pages in the "
                "narrower TMLR block, and let tables drift above their own heading"
            )

        if stripped.startswith("\\begin{document}"):
            out.append("\\title{" + TITLE + "}")
            out.append("")
            out.append("%% Author order follows the amended public v2.6 PDF; DK-02 confirms it")
            out.append("%% with all three authors. The anonymous build hides this block.")
            out.append(AUTHOR)
            out.append("")
            out.append("\\begin{document}")
            out.append("")
            out.append("\\maketitle")
            log.append("replaced the centred title block with TMLR \\title/\\author/\\maketitle")
            # skip the original centred block
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("\\end{center}"):
                i += 1
            i += 1
            continue

        # PDF metadata must not carry the authors in the anonymous build
        if "pdfauthor=" in stripped:
            out.append("  pdfauthor={\\pdfauthorlist},")
            log.append(
                "pdfauthor now expands \\pdfauthorlist, which each wrapper defines "
                "(empty for the anonymous build) - otherwise the metadata leaks the authors"
            )
            i += 1
            continue

        if stripped.startswith("\\bibliographystyle{plainnat}"):
            out.append("\\bibliographystyle{tmlr}")
            log.append("bibliography style plainnat -> tmlr (TMLR's author-year style)")
            i += 1
            continue

        out.append(line)
        i += 1

    body = "\n".join(out) + "\n"
    for old, new, reason in LAYOUT_FIXES:
        if old not in body:
            raise SystemExit(f"layout fix no longer matches the source: {reason}")
        body = body.replace(old, new)
        log.append(f"layout: {reason}")

    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "paper_common.tex").write_text(body)
    (outdir / "tmlr_submission.tex").write_text(
        WRAPPER.format(mode="anonymous (submission)", option="", authors="")
    )
    (outdir / "tmlr_named.tex").write_text(
        WRAPPER.format(
            mode="named (internal review)",
            option="\\PassOptionsToPackage{preprint}{tmlr}\n",
            authors="Chengshuai Yang and Ting Xue and Dingyi Kang",
        )
    )
    for name in ("tmlr.sty", "tmlr.bst", "fancyhdr.sty"):
        shutil.copy(template / name, outdir / name)
    for name in ("references.bib", "fig_hsc.pdf", "fig_regime.pdf"):
        shutil.copy(source / name, outdir / name)
    log.append(f"copied the TMLR style files, references.bib and both figures into {outdir.name}/")
    return log


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True, type=Path)
    ap.add_argument("--template", required=True, type=Path)
    ap.add_argument("--outdir", required=True, type=Path)
    args = ap.parse_args()
    for entry in convert(args.source, args.outdir, args.template):
        print(entry)


if __name__ == "__main__":
    main()
